# Main configuration for Hyperliquid Trading Bot

# Hyperliquid DEX Configuration
hyperliquid:
  api_url: "https://api.hyperliquid.xyz"
  ws_url: "wss://api.hyperliquid.xyz/ws"
  wallet_address: "${WALLET_ADDRESS}"
  private_key: "${PRIVATE_KEY}"
  testnet: false

# LangChain Configuration
langchain:
  llm_provider: "${LLM_PROVIDER:openai}"
  model: "${LLM_MODEL:gpt-4-turbo}"
  temperature: 0.1
  max_tokens: 2000
  vector_db: "chroma"
  vector_db_path: "./data/vectors"
  tracing: true
  project: "hyperliquid-trading-bot"

# Trading Configuration
trading:
  max_position_size: 0.1  # 10% of portfolio per position
  max_positions: 5
  default_leverage: 2
  risk_per_trade: 0.02  # 2% risk per trade
  min_position_size: 0.001
  max_leverage: 10

# Risk Management
risk:
  use_stop_loss: true
  use_take_profit: true
  default_stop_loss_percent: 2.0  # 2% stop loss
  default_take_profit_percent: 5.0  # 5% take profit
  max_daily_loss: 5.0  # 5% max daily loss
  max_drawdown: 10.0  # 10% max drawdown

# Strategy Configuration
strategies:
  active:
    - name: "trend_following"
      enabled: true
      params:
        timeframe: "1h"
        indicators: ["EMA", "RSI", "MACD"]
        ema_period: 20
        rsi_period: 14
        rsi_oversold: 30
        rsi_overbought: 70

# Database Configuration
databases:
  # Vector DB for RAG
  vector_db:
    type: "chroma"
    path: "./data/vectors"
    collection_name: "market_knowledge"

  # Time-series DB
  timeseries_db:
    type: "influxdb"
    url: "${INFLUXDB_URL:http://localhost:8086}"
    token: "${INFLUXDB_TOKEN}"
    org: "${INFLUXDB_ORG}"
    bucket: "${INFLUXDB_BUCKET:trading_data}"

  # State management (Redis)
  state_db:
    type: "redis"
    url: "${REDIS_URL:redis://localhost:6379}"
    db: 0

# Monitoring Configuration
monitoring:
  enabled: true
  prometheus:
    enabled: true
    port: 9090
  grafana:
    enabled: false
    port: 3000

# Logging Configuration
logging:
  level: "${LOG_LEVEL:INFO}"
  format: "<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan> - <level>{message}</level>"
  rotation: "500 MB"
  retention: "10 days"
  log_dir: "./data/logs"

# Performance Configuration
performance:
  enable_caching: true
  cache_ttl: 300  # 5 minutes
  max_concurrent_requests: 10
  request_timeout: 30  # seconds
  websocket_reconnect_delay: 5  # seconds
