# Logging configuration

version: 1
disable_existing_loggers: false

formatters:
  default:
    format: "<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan> - <level>{message}</level>"

  simple:
    format: "{time:HH:mm:ss} | {level} | {message}"

  detailed:
    format: "{time:YYYY-MM-DD HH:mm:ss.SSS} | {level: <8} | {name}:{function}:{line} - {message}"

handlers:
  console:
    level: INFO
    format: default
    colorize: true

  file:
    level: DEBUG
    format: detailed
    rotation: "500 MB"
    retention: "10 days"
    compression: "zip"

  error_file:
    level: ERROR
    format: detailed
    rotation: "100 MB"
    retention: "30 days"

loggers:
  src.core:
    level: DEBUG
    handlers: [console, file]

  src.agents:
    level: DEBUG
    handlers: [console, file]

  src.services:
    level: INFO
    handlers: [console, file]

  src.storage:
    level: INFO
    handlers: [console, file]

# Log levels: TRACE, DEBUG, INFO, SUCCESS, WARNING, ERROR, CRITICAL
