# Strategy-specific parameters and configurations

strategies:
  # Trend Following Strategy
  trend_following:
    description: "Follow established trends using EMA crossovers and momentum"
    enabled: true
    params:
      timeframe: "1h"
      ema_short: 12
      ema_long: 26
      rsi_period: 14
      rsi_oversold: 30
      rsi_overbought: 70
      volume_threshold: 1.5  # Volume must be 1.5x average
      min_trend_strength: 0.6  # 0-1 scale

  # Mean Reversion Strategy
  mean_reversion:
    description: "Trade price returns to moving average"
    enabled: false
    params:
      timeframe: "15m"
      sma_period: 20
      bollinger_period: 20
      bollinger_std: 2
      rsi_period: 14
      rsi_extreme_low: 25
      rsi_extreme_high: 75
      max_distance_from_mean: 2.5  # Standard deviations

  # Breakout Strategy
  breakout:
    description: "Trade breakouts from consolidation ranges"
    enabled: false
    params:
      timeframe: "1h"
      lookback_period: 20
      volume_confirmation: true
      min_volume_increase: 2.0
      retest_entry: false
      consolidation_threshold: 0.02  # 2% range

  # AI Decision Strategy
  ai_decision:
    description: "LangChain AI agent makes trading decisions"
    enabled: true
    params:
      model: "gpt-4-turbo"
      temperature: 0.1
      use_rag: true
      sentiment_weight: 0.3
      technical_weight: 0.7
      confidence_threshold: 0.7
      max_reasoning_steps: 5

# Backtesting Configuration
backtesting:
  initial_capital: 10000
  commission: 0.001  # 0.1%
  slippage: 0.0005  # 0.05%
  start_date: "2024-01-01"
  end_date: "2024-12-31"
  timeframe: "1h"

# Strategy Performance Metrics
metrics:
  track:
    - "total_return"
    - "sharpe_ratio"
    - "max_drawdown"
    - "win_rate"
    - "profit_factor"
    - "average_trade"
    - "trades_per_day"

  targets:
    min_sharpe_ratio: 1.5
    max_drawdown: -15.0  # Percent
    min_win_rate: 0.55  # 55%
    min_profit_factor: 1.8
